version: '3.8'

services:
  pokeserbia-bot:
    image: ghcr.io/numulix/ptcg-scraper-discord-bot:latest
    container_name: pokeserbia-bot
    restart: unless-stopped

    environment:
      - NODE_ENV=production
    
    env_file:
      - ./.env
    
    volumes:
      - ./data:/usr/src/app/data