version: '3.8'

services:
  pokeserbia-bot:
    container_name: pokeserbia-bot-local-test
    restart: unless-stopped

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - NODE_ENV=production
    
    env_file:
      - ./.env
    
    volumes:
      - ./data:/usr/src/app/data